export const SITE_CONFIG = {
  companyName: "KASH Technology",
  tagline: "TAILORED | AFFORDABLE | SCALABLE",
  subTagline: "Custom Software Development Agency",
  websiteUrl: process.env.NEXT_PUBLIC_SITE_URL || "https://www.kash-technology.com",
  contactEmail: process.env.CONTACT_RECEIVER_EMAIL || "founder@kash-technology.com",
  contactPhonePrimary: "+91 97609 42003",
  contactPhoneAlternate: "+91 97606 58804",
  whatsappNumber: "+91 97609 42003",
  whatsappUrl: "https://wa.me/919760942003?text=Hello%20KASH%20Technology%2C%20I%27d%20like%20to%20discuss%20a%20project.",
  bookingUrl: process.env.NEXT_PUBLIC_BOOKING_URL || "/contact#consultation",
  locationText: "Serving clients remotely across India & internationally",
  social: {
    linkedin: "https://linkedin.com/company/kash-technology",
    github: "https://github.com/kash-technology",
    facebook: "",
    twitter: "",
    instagram: "",
    youtube: "",
  },
  navLinks: [
    { label: "Home", href: "/" },
    { label: "Services", href: "/services" },
    { label: "Solutions", href: "/solutions" },
    { label: "Portfolio", href: "/portfolio" },
    { label: "About", href: "/about" },
    { label: "Contact", href: "/contact" },
  ],
  servicesList: [
    { name: "Web Development", href: "/services" },
    { name: "Mobile Apps", href: "/services" },
    { name: "Custom Software", href: "/services" },
    { name: "AI Automation", href: "/services" },
    { name: "ERP / CRM Systems", href: "/services" },
    { name: "E-commerce Solutions", href: "/services" },
  ],
  products: {
    exora: {
      name: "Exora",
      tagline: "High-Performance Crypto Trading Platform",
      caseStudyPath: "/work/exora",
      externalUrl: "https://exora-crypto-platform.vercel.app",
    },
    schoolsync: {
      name: "SchoolSync",
      tagline: "Unified School Management ERP & Analytics",
      caseStudyPath: "/work/schoolsync",
      externalUrl: "https://school-sync-pro.vercel.app",
    },
    launchpad: {
      name: "Crypto Launchpad",
      tagline: "Token Launch & Presale Deployment Protocol",
      caseStudyPath: "/work/crypto-launchpad",
      externalUrl: "https://crypto-launchedpad-mvp.vercel.app",
    },
  },
} as const;
